name: SAST CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}
      PROJECT: rodv-elasticsearch
      BLDCMD: ./gradlew :distribution:archives:linux-tar:assemble

    steps:
    - uses: actions/checkout@v1
    - name: Set up JRE 17
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 17      
        
    - name: Full SAST
      run: |
        curl -fLOsS $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
        unzip -d /tmp -jo polaris_cli-linux64.zip
        /tmp/polaris --co project.name=$PROJECT analyze -w -- $BLDCMD   
