name: SCA CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JRE 17
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 17
        
    - name: Build with Gradle
      run: ./gradlew clean && ./gradlew :distribution:archives:linux-tar:assemble
      
    - name: Upload to CoPilot
      if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      run: bash <(curl -s https://copilot.blackducksoftware.com/ci/githubactions/scripts/upload)
